# Generated by Django 6.0.3 on 2026-03-21 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasstimeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('question_set_id', models.CharField(blank=True, max_length=100)),
                ('session_type', models.CharField(choices=[('practice', 'Practice'), ('assessment', 'Assessment')], default='practice', max_length=20)),
                ('status', models.CharField(default='created', max_length=50)),
                ('questions_data', models.JSONField(blank=True, default=list)),
                ('student_url', models.CharField(blank=True, max_length=500)),
                ('secret_link', models.CharField(blank=True, max_length=100)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('results_synced_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classtime_sessions', to='lessons.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classtime_sessions', to='accounts.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classtime_sessions', to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='classtime_sessions.classtimesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='classtimesession',
            index=models.Index(fields=['teacher', '-created_at'], name='classtime_s_teacher_53405d_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimesession',
            index=models.Index(fields=['student', '-created_at'], name='classtime_s_student_7eb739_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimesession',
            index=models.Index(fields=['lesson'], name='classtime_s_lesson__144fa8_idx'),
        ),
    ]
