# Generated by Django 6.0.3 on 2026-03-21 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classtime_sessions', '0001_initial'),
        ('skill_results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_index', models.IntegerField()),
                ('classtime_question_id', models.CharField(blank=True, max_length=100)),
                ('question_type', models.CharField(max_length=50)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('stem', models.TextField()),
                ('source_error_ref', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField()),
                ('student_answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='classtimesession',
            name='question_skill_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classtime_sessions', to='skill_results.skillexecution'),
        ),
    ]
