# Generated by Django 6.0.3 on 2026-03-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classtime_sessions', '0002_practicequestion_practiceresult_and_more'),
        ('learning_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='error_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_questions', to='learning_progress.errorpattern'),
        ),
    ]
