# Generated by Django 6.0.3 on 2026-03-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classtime_sessions', '0003_practicequestion_error_pattern'),
        ('skill_results', '0002_skillexecution_parsed_at_errorrecord_lessontheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='error_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_questions', to='skill_results.errorrecord'),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to='classtime_sessions.classtimesession'),
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_results', to='classtime_sessions.sessionparticipant'),
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='practice_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classtime_sessions.practicequestion'),
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['session', 'question_index'], name='classtime_s_session_1ee09e_idx'),
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['error_record'], name='classtime_s_error_r_581bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['error_pattern'], name='classtime_s_error_p_444ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceresult',
            index=models.Index(fields=['participant', '-answered_at'], name='classtime_s_partici_dad372_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceresult',
            index=models.Index(fields=['practice_question', 'is_correct'], name='classtime_s_practic_6d7aef_idx'),
        ),
    ]
