# Generated by Django 6.0.3 on 2026-03-21 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPatternOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonLevelAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_level', models.CharField(max_length=10)),
                ('range_level', models.CharField(blank=True, max_length=10)),
                ('accuracy_level', models.CharField(blank=True, max_length=10)),
                ('fluency_level', models.CharField(blank=True, max_length=10)),
                ('interaction_level', models.CharField(blank=True, max_length=10)),
                ('coherence_level', models.CharField(blank=True, max_length=10)),
                ('strengths', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('zpd_lower', models.CharField(blank=True, max_length=10)),
                ('zpd_upper', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern_key', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=255)),
                ('error_type', models.CharField(max_length=50)),
                ('error_subtype', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('recurring', 'Recurring'), ('improving', 'Improving'), ('mastered', 'Mastered')], db_index=True, default='new', max_length=20)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('occurrence_count', models.IntegerField(default=1)),
                ('lesson_count', models.IntegerField(default=1)),
                ('times_tested', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('mastery_score', models.FloatField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to='accounts.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_error_patterns', to='accounts.teacher')),
            ],
        ),
    ]
