# Generated by Django 6.0.3 on 2026-03-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning_progress', '0001_initial'),
        ('lessons', '0001_initial'),
        ('skill_results', '0002_skillexecution_parsed_at_errorrecord_lessontheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpatternoccurrence',
            name='error_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_occurrences', to='skill_results.errorrecord'),
        ),
        migrations.AddField(
            model_name='errorpatternoccurrence',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_pattern_occurrences', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='errorpatternoccurrence',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='learning_progress.errorpattern'),
        ),
        migrations.AddField(
            model_name='lessonlevelassessment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assessments', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='lessonlevelassessment',
            name='skill_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assessments', to='skill_results.skillexecution'),
        ),
        migrations.AddField(
            model_name='lessonlevelassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assessments', to='accounts.student'),
        ),
        migrations.AddIndex(
            model_name='errorpattern',
            index=models.Index(fields=['student', 'status'], name='learning_pr_student_c48aff_idx'),
        ),
        migrations.AddIndex(
            model_name='errorpattern',
            index=models.Index(fields=['student', '-occurrence_count'], name='learning_pr_student_948361_idx'),
        ),
        migrations.AddIndex(
            model_name='errorpattern',
            index=models.Index(fields=['teacher', 'student', 'status'], name='learning_pr_teacher_d8b691_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='errorpattern',
            unique_together={('student', 'teacher', 'pattern_key')},
        ),
        migrations.AddIndex(
            model_name='errorpatternoccurrence',
            index=models.Index(fields=['pattern', '-created_at'], name='learning_pr_pattern_9c0ba6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='errorpatternoccurrence',
            unique_together={('pattern', 'error_record')},
        ),
        migrations.AddIndex(
            model_name='lessonlevelassessment',
            index=models.Index(fields=['student', '-created_at'], name='learning_pr_student_e4f208_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonlevelassessment',
            index=models.Index(fields=['student', 'overall_level'], name='learning_pr_student_411ba3_idx'),
        ),
    ]
