# Generated by Django 6.0.3 on 2026-03-21 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoiceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_id", models.UUIDField(help_text="Student who practiced")),
                (
                    "lesson_id",
                    models.UUIDField(help_text="Source lesson for errors/themes"),
                ),
                (
                    "agent_id",
                    models.CharField(
                        help_text="Agora ConvoAI agent ID", max_length=255
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="Agora RTC channel name", max_length=255
                    ),
                ),
                (
                    "classtime_session_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Classtime session code for quiz bridge",
                        max_length=50,
                    ),
                ),
                (
                    "mastery_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Final mastery state: errors, quiz results, biomarkers",
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="When session ended", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
