# Generated by Django 6.0.3 on 2026-03-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicesession",
            name="lesson_id",
            field=models.CharField(
                help_text="Source lesson for errors/themes", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="voicesession",
            name="student_id",
            field=models.CharField(help_text="Student who practiced", max_length=255),
        ),
    ]
