# Generated by Django 6.0.3 on 2026-03-21 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(max_length=50)),
                ('subject_config', models.JSONField(blank=True, default=dict)),
                ('current_level', models.CharField(blank=True, max_length=50)),
                ('goal', models.TextField(blank=True)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('total_lessons', models.IntegerField(default=0)),
                ('last_lesson_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], db_index=True, default='active', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_relationships', to='accounts.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_relationships', to='accounts.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'student', 'subject_type')},
            },
        ),
    ]
