# Generated by Django 6.0.3 on 2026-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrelationship',
            name='preply_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
