# Generated by Django 6.0.3 on 2026-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_tutoringrelationship_preply_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrelationship',
            name='active_error_patterns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutoringrelationship',
            name='latest_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tutoringrelationship',
            name='latest_level_assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringrelationship',
            name='mastered_error_patterns',
            field=models.IntegerField(default=0),
        ),
    ]
