# Generated by Django 6.0.3 on 2026-03-21 09:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preply_user_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('classtime_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('classtime_token', models.TextField(blank=True, default='')),
                ('classtime_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preply_user_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('classtime_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('classtime_token', models.TextField(blank=True, default='')),
                ('classtime_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
