# DailyBriefing storage and retrieval
#
# Functions planned:
#   create_briefing(teacher, date, data, student_reports) → DailyBriefing
#   get_briefing(teacher_id, date=None) → DailyBriefing
#
# One briefing per teacher per day, generated by prepare-daily-briefing skill.
#
# See: docs/conversational-ux.md (MVP mode 1: daily_briefing)
